---
title: "Insper Survey"
author: "Felipe Tufaile"
date: "`r Sys.Date()`"
output: html_document
---


```{r configs, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, include = TRUE, message = FALSE)
```


## Loading libraries

```{r libraries}

## Set working directory
setwd("~/Insper/Marketing Analytics")

# options(download.file.method = "wininet") ## isntall factoextra for windows
# install_github("kassambara/factoextra")
# inlibrary(factoextra)

library(dplyr)
library(tidyverse)
library(ggthemes)
library(gridExtra)
library(factoextra)
```


```{r pca_plot}
## Reading the dataset
df <- read_csv("Insper_vFMT_3.csv", show_col_types = FALSE)

## Adjusting the dataframe
df_clean <- df %>%
  mutate(id=1) %>%
  pivot_longer(!id, names_to = "variable", values_to = "values") %>%
  mutate(variable_name = str_split_fixed(variable, "_", 2)[,1],
         university = str_split_fixed(variable, "_", 2)[,2],) %>%
  select(variable_name, university, values) %>%
  rename(variable = variable_name) %>%
  mutate(variable = case_when(variable == 'conhetech' ~ 'conhecimento tecnico',
                              variable == 'reconhmerca' ~ 'reconhecimento no mercado',
                              variable == 'empreende' ~ 'empreendedorismo',
                              variable == 'custobene' ~ 'custo beneficio',
                              variable == 'infra' ~ 'infraestrutura',
                              variable == 'corpdocen' ~ 'corpo docente',
                              variable == 'relinterpess' ~ 'relacao interpessoal',
                              variable == 'relprofiss' ~ 'relacao profissional',
                              variable == 'conhalemtech' ~ 'conhecimento alem do tecnico',
                              variable == 'demasregra' ~ 'regras demasiadas',
                              variable == 'pref' ~ 'grau de preferencia',
                              TRUE ~ variable)) %>%
  pivot_wider(names_from = variable, values_from = values) %>%
  mutate(university = case_when(university == 'mack' ~ 'MACKENZIE',
                                university == 'poli' ~ 'POLI',
                                university == 'sc' ~ 'USP',
                                university == 'fei' ~ 'FEI',
                                university == 'ita' ~ 'ITA',
                                university == 'insper' ~ 'INSPER',
                                university == 'maua' ~ 'MAUA',
                                TRUE ~ university)) %>%
  column_to_rownames('university')
  

## Calculating principal components
pc.cr <- df_clean %>% prcomp(cor = TRUE)

## Dimensions
summary(pc.cr)

## Loadings
pc.cr$x

## PCA Plot
fviz_pca_biplot(pc.cr, repel = TRUE)+
  labs(title = "Feature attributes proximities between universities (MultiDimensional Scaling)",
       caption='Fonte: Marketing Analytics - Insper') +
  theme_few()+
  theme(panel.border = element_blank(),
        axis.line = element_line(colour = "black"),
        plot.caption = element_text(hjust=0,
                                    vjust=-0.5,size=8))
```
  